version: '3.0'

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: "speedcentral"
      POSTGRES_PASSWORD: dev
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
      - ./local_data.sql:/docker-entrypoint-initdb.d/local_data.sql:ro
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8081:8080
